import type { Product } from "@/services/productService"

// Demo products for when Supabase isn't configured
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Quantum Pro Wireless Headphones",
    description: "Experience immersive 3D spatial audio with our flagship noise-cancelling headphones. Features 40-hour battery life, premium titanium drivers, and adaptive transparency mode.",
    price: 2999,
    image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80",
    stock: 45,
    seller_id: "demo-seller",
    category: "electronics",
    rating: 4.8,
    review_count: 234,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Nebula Smart Watch Ultra",
    description: "The most advanced smartwatch with holographic display, health monitoring suite, and 7-day battery life. Water resistant to 100m.",
    price: 4999,
    image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80",
    stock: 28,
    seller_id: "demo-seller",
    category: "electronics",
    rating: 4.9,
    review_count: 189,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Aurora Designer Backpack",
    description: "Handcrafted from premium Italian leather with anti-theft compartments, USB charging port, and ergonomic design for urban professionals.",
    price: 1899,
    image_url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
    stock: 67,
    seller_id: "demo-seller",
    category: "fashion",
    rating: 4.6,
    review_count: 156,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Prism LED Smart Desk Lamp",
    description: "Ambient lighting reimagined. 16 million colors, app-controlled, circadian rhythm modes, and wireless charging base.",
    price: 1299,
    image_url: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=500&q=80",
    stock: 92,
    seller_id: "demo-seller",
    category: "home",
    rating: 4.7,
    review_count: 312,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Velocity Running Shoes X1",
    description: "Carbon fiber plate technology with responsive foam cushioning. Designed for elite runners seeking maximum speed and comfort.",
    price: 2499,
    image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80",
    stock: 34,
    seller_id: "demo-seller",
    category: "sports",
    rating: 4.5,
    review_count: 98,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Obsidian Ceramic Pour-Over Set",
    description: "Japanese-inspired minimalist coffee set. Hand-glazed ceramic with precision drip system for the perfect brew every time.",
    price: 899,
    image_url: "https://images.unsplash.com/photo-1572119865084-43c285814d63?w=500&q=80",
    stock: 120,
    seller_id: "demo-seller",
    category: "home",
    rating: 4.8,
    review_count: 267,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Aether Noise-Cancelling Earbuds",
    description: "True wireless earbuds with crystal-clear ANC, 32-hour battery with case, and IPX7 waterproofing for any environment.",
    price: 1999,
    image_url: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=500&q=80",
    stock: 55,
    seller_id: "demo-seller",
    category: "electronics",
    rating: 4.4,
    review_count: 445,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Luxe Botanical Skincare Set",
    description: "Premium organic skincare collection: cleanser, toner, serum, and moisturizer. Dermatologist tested, cruelty-free, glass packaging.",
    price: 1599,
    image_url: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&q=80",
    stock: 78,
    seller_id: "demo-seller",
    category: "beauty",
    rating: 4.9,
    review_count: 523,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Titan Mechanical Keyboard",
    description: "Custom hot-swappable mechanical keyboard with RGB per-key lighting, PBT keycaps, gasket mount, and aluminum frame.",
    price: 1799,
    image_url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&q=80",
    stock: 42,
    seller_id: "demo-seller",
    category: "electronics",
    rating: 4.7,
    review_count: 198,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    title: "Zenith Yoga Mat Premium",
    description: "Natural rubber yoga mat with alignment guides, antimicrobial surface, and carrying strap. 6mm extra-cushion thickness.",
    price: 799,
    image_url: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&q=80",
    stock: 150,
    seller_id: "demo-seller",
    category: "sports",
    rating: 4.6,
    review_count: 87,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    title: "Horizon Polarized Sunglasses",
    description: "Titanium frame polarized sunglasses with UV400 protection. Lightweight, scratch-resistant lenses in a modern aviator design.",
    price: 2199,
    image_url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&q=80",
    stock: 63,
    seller_id: "demo-seller",
    category: "fashion",
    rating: 4.5,
    review_count: 142,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    title: "Echo Smart Speaker Hub",
    description: "Premium multi-room smart speaker with 360° spatial audio, built-in home automation hub, and voice AI assistant.",
    price: 2999,
    image_url: "https://images.unsplash.com/photo-1558089687-f282d8b1b1b1?w=500&q=80",
    stock: 38,
    seller_id: "demo-seller",
    category: "electronics",
    rating: 4.3,
    review_count: 176,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
]

export const DEMO_TESTIMONIALS = [
  {
    id: "1",
    name: "Sarah Chen",
    role: "Product Designer",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    content: "Urban-Basket has completely transformed my shopping experience. The quality of products and lightning-fast delivery is unmatched.",
    rating: 5,
  },
  {
    id: "2",
    name: "Marcus Rivera",
    role: "Software Engineer",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    content: "The curated selection is incredible. Every product I've purchased exceeded my expectations. This is the future of e-commerce.",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Watson",
    role: "Creative Director",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    content: "As a seller, the dashboard analytics are game-changing. I can track everything in real-time. Revenue has increased 40% since joining.",
    rating: 5,
  },
  {
    id: "4",
    name: "David Kim",
    role: "Entrepreneur",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    content: "The seller tools are incredibly powerful yet simple to use. Managing inventory and orders has never been this seamless.",
    rating: 4,
  },
]
