import type { MysteryBox } from "@/services/mysteryBoxService"

/** Shown when API is down or DB has no rows yet. */
export const MYSTERY_BOXES_FALLBACK: MysteryBox[] = [
  {
    id: "mb-budget-001",
    slug: "budget-mystery-box",
    title: "Budget Mystery Box",
    description: "Surprise picks — perfect starter loot.",
    price: 499,
    image_url: "https://images.unsplash.com/photo-1607083206869-4c6672c72b65?w=600&q=80",
    tier: "budget",
    category_filter: null,
    min_items: 2,
    max_items: 3,
    stock: 200,
  },
  {
    id: "mb-electronics-001",
    slug: "electronics-mystery-box",
    title: "Electronics Mystery Box",
    description: "Gadgets worth more than you pay.",
    price: 1999,
    image_url: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&q=80",
    tier: "electronics",
    category_filter: "electronics",
    min_items: 1,
    max_items: 2,
    stock: 150,
  },
  {
    id: "mb-fashion-001",
    slug: "fashion-mystery-box",
    title: "Fashion Mystery Box",
    description: "Curated style essentials.",
    price: 1499,
    image_url: "https://images.unsplash.com/photo-1483985988354-763728e3685b?w=600&q=80",
    tier: "fashion",
    category_filter: "fashion",
    min_items: 2,
    max_items: 3,
    stock: 150,
  },
  {
    id: "mb-premium-001",
    slug: "premium-mystery-box",
    title: "Premium Mystery Box",
    description: "High-value flagship surprises.",
    price: 4999,
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80",
    tier: "premium",
    category_filter: null,
    min_items: 2,
    max_items: 4,
    stock: 80,
  },
  {
    id: "mb-gaming-001",
    slug: "gaming-mystery-box",
    title: "Gaming Mystery Box",
    description: "Neon-ready gaming gear.",
    price: 2499,
    image_url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80",
    tier: "gaming",
    category_filter: "toys",
    min_items: 2,
    max_items: 3,
    stock: 120,
  },
]
